# Generated by Django 3.0.6 on 2020-12-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotnot', '0003_auto_20201209_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
