# Generated by Django 3.0.6 on 2020-12-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotnot', '0005_auto_20201211_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hot_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='not_vote',
            field=models.IntegerField(default=0),
        ),
    ]
