# Generated by Django 3.0.6 on 2020-12-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotnot', '0006_auto_20201211_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
